# Variable 'goal' was defined in the Variables tab
# Variable Group 'Sonar' was defined in the Variables tab
variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
trigger:
- main
pool:
  vmImage: ubuntu-latest
  include:
    - refs/heads/master
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Phase_1