# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    export JAVA_OPTIONS: '-Xms=1024m -Xmx=4096m -MaxPermSize=500m'
    artifactoryResolverService: 'art2'
    targetResolveReleaseRepo: 'manu-libs-release'
    targetResolveSnapshotRepo: 'manu-libs-snapshot'
    artifactoryDeployService: 'art2'
    targetDeployReleaseRepo: 'manu-libs-release'
    targetDeploySnapshotRepo: 'manu-libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'art2'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'