# Variable 'goal' was defined in the Variables tab
# Variable Group 'Sonar' was defined in the Variables tab
variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
trigger:
- main
pool:
  vmImage: ubuntu-latest
steps: 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      set MAVEN_OPTS="-Xms1024m -Xmx4096m -client -XX:MaxPermSize=500m  -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none"
       write-host "before: $($env:MAVEN_OPTS)"
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$env:MAVEN_OPTS="-Xms1024m -Xmx4096m -client -XX:MaxPermSize=500m  -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'

- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    options: -DXms=100m -DXmx=10m -DMaxPermSize=10m
    artifactoryResolverService: 'art2'
    targetResolveReleaseRepo: 'manu-libs-release'
    targetResolveSnapshotRepo: 'manu-libs-snapshot'
    artifactoryDeployService: 'art2'
    targetDeployReleaseRepo: 'manu-libs-release'
    targetDeploySnapshotRepo: 'manu-libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'write-host "$($env:MAVEN_OPTS)"'


