# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts2-art'
    cliInstallationRepo: 'jfrog-cli-v2-new'
    installCustomVersion: true
    cliVersion: '2.62.1'
    installExtractors: true
    extractorsInstallationRepo: 'extractors'
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'myartnew'
    targetResolveReleaseRepo: 'azuremvn-libs-release'
    targetResolveSnapshotRepo: 'azuremvn-libs-snapshot'
    artifactoryDeployService: 'myartnew'
    targetDeployReleaseRepo: 'azuremvn-libs-release'
    targetDeploySnapshotRepo: 'azuremvn-libs-snapshot'
    collectBuildInfo: 'true'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'myartnew'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true 

- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'myxray'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false
    vuln: true