# Variable 'goal' was defined in the Variables tab
# Variable Group 'Sonar' was defined in the Variables tab
variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
trigger:
- main
pool:
  vmImage: ubuntu-latest
steps: 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      set MAVEN_OPTS="-Xms1024m -Xmx4096m -client -XX:MaxPermSize=500m  -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none"
       write-host "before: $($env:MAVEN_OPTS)"