# Variable 'goal' was defined in the Variables tab
# Variable Group 'Sonar' was defined in the Variables tab
variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
trigger:
- main
pool:
  vmImage: ubuntu-latest
jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
  - task: Maven@3
    displayName: Maven pom.xml
    enabled: False
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'install'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Path'
      mavenSetM2Home: false
      mavenOptions: '-Xms512m -Xmx1024m'
      mavenAuthenticateFeed: true
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  - task: ArtifactoryToolsInstaller@1
    displayName: Using Jfrog CLI 1.54.0
    inputs:
      artifactoryService: 'art1'
      cliInstallationRepo: 'manu-libs-release'
      installCustomVersion: true
      cliVersion: '1.54.0'
  - task: JavaToolInstaller@0
    displayName: Use Java 11
    inputs:
      versionSpec: 11
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled
  - task: PowerShell@2
    displayName: Set MAVEN_OPTS
    inputs:
      targetType: inline
      script: >-
        $env:MAVEN_OPTS="-Xms1024m -Xmx4096m -client -XX:MaxPermSize=500m  -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none"

        write-host "before: $($env:MAVEN_OPTS)"
  - task: PowerShell@2
    displayName: MAVEN_OPTS after maven step
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      script: write-host "$($env:MAVEN_OPTS)"